// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: emailService/proto/email.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailService_proto_email_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_emailService_proto_email_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_emailService_proto_email_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailId *Email `protobuf:"bytes,1,opt,name=emailId,proto3" json:"emailId,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailService_proto_email_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_emailService_proto_email_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_emailService_proto_email_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetEmailId() *Email {
	if x != nil {
		return x.EmailId
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailService_proto_email_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_emailService_proto_email_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_emailService_proto_email_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type Sendgrid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailID string `protobuf:"bytes,1,opt,name=emailID,proto3" json:"emailID,omitempty"`
	Body    string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Sendgrid) Reset() {
	*x = Sendgrid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailService_proto_email_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sendgrid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sendgrid) ProtoMessage() {}

func (x *Sendgrid) ProtoReflect() protoreflect.Message {
	mi := &file_emailService_proto_email_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sendgrid.ProtoReflect.Descriptor instead.
func (*Sendgrid) Descriptor() ([]byte, []int) {
	return file_emailService_proto_email_proto_rawDescGZIP(), []int{3}
}

func (x *Sendgrid) GetEmailID() string {
	if x != nil {
		return x.EmailID
	}
	return ""
}

func (x *Sendgrid) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendgridRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailMetadata *Sendgrid `protobuf:"bytes,1,opt,name=emailMetadata,proto3" json:"emailMetadata,omitempty"`
}

func (x *SendgridRequest) Reset() {
	*x = SendgridRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailService_proto_email_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendgridRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendgridRequest) ProtoMessage() {}

func (x *SendgridRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emailService_proto_email_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendgridRequest.ProtoReflect.Descriptor instead.
func (*SendgridRequest) Descriptor() ([]byte, []int) {
	return file_emailService_proto_email_proto_rawDescGZIP(), []int{4}
}

func (x *SendgridRequest) GetEmailMetadata() *Sendgrid {
	if x != nil {
		return x.EmailMetadata
	}
	return nil
}

type SendGridResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *SendGridResponse) Reset() {
	*x = SendGridResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailService_proto_email_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGridResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGridResponse) ProtoMessage() {}

func (x *SendGridResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emailService_proto_email_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGridResponse.ProtoReflect.Descriptor instead.
func (*SendGridResponse) Descriptor() ([]byte, []int) {
	return file_emailService_proto_email_proto_rawDescGZIP(), []int{5}
}

func (x *SendGridResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

var File_emailService_proto_email_proto protoreflect.FileDescriptor

var file_emailService_proto_email_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x73, 0x72, 0x63, 0x22, 0x17, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x07, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x72, 0x63,
	0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x07, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x22,
	0x1c, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x38, 0x0a,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x67, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x46, 0x0a, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x67,
	0x72, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0d, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x67, 0x72, 0x69, 0x64,
	0x52, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x24, 0x0a, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x72, 0x65, 0x73, 0x32, 0x3b, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0c, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x51, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x69, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x69,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x73,
	0x65, 0x6e, 0x64, 0x67, 0x72, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x73, 0x72, 0x63, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x69, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_emailService_proto_email_proto_rawDescOnce sync.Once
	file_emailService_proto_email_proto_rawDescData = file_emailService_proto_email_proto_rawDesc
)

func file_emailService_proto_email_proto_rawDescGZIP() []byte {
	file_emailService_proto_email_proto_rawDescOnce.Do(func() {
		file_emailService_proto_email_proto_rawDescData = protoimpl.X.CompressGZIP(file_emailService_proto_email_proto_rawDescData)
	})
	return file_emailService_proto_email_proto_rawDescData
}

var file_emailService_proto_email_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_emailService_proto_email_proto_goTypes = []interface{}{
	(*Email)(nil),            // 0: src.Email
	(*Request)(nil),          // 1: src.request
	(*Response)(nil),         // 2: src.response
	(*Sendgrid)(nil),         // 3: src.sendgrid
	(*SendgridRequest)(nil),  // 4: src.sendgridRequest
	(*SendGridResponse)(nil), // 5: src.sendGridResponse
}
var file_emailService_proto_email_proto_depIdxs = []int32{
	0, // 0: src.request.emailId:type_name -> src.Email
	3, // 1: src.sendgridRequest.emailMetadata:type_name -> src.sendgrid
	1, // 2: src.EmailService.EmailService:input_type -> src.request
	4, // 3: src.SendGridService.SendGridService:input_type -> src.sendgridRequest
	2, // 4: src.EmailService.EmailService:output_type -> src.response
	5, // 5: src.SendGridService.SendGridService:output_type -> src.sendGridResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_emailService_proto_email_proto_init() }
func file_emailService_proto_email_proto_init() {
	if File_emailService_proto_email_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_emailService_proto_email_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailService_proto_email_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailService_proto_email_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailService_proto_email_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sendgrid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailService_proto_email_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendgridRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailService_proto_email_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGridResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emailService_proto_email_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_emailService_proto_email_proto_goTypes,
		DependencyIndexes: file_emailService_proto_email_proto_depIdxs,
		MessageInfos:      file_emailService_proto_email_proto_msgTypes,
	}.Build()
	File_emailService_proto_email_proto = out.File
	file_emailService_proto_email_proto_rawDesc = nil
	file_emailService_proto_email_proto_goTypes = nil
	file_emailService_proto_email_proto_depIdxs = nil
}
