// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: emailService/proto/email.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailServiceClient interface {
	EmailService(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type emailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailServiceClient(cc grpc.ClientConnInterface) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) EmailService(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/src.EmailService/EmailService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceServer is the server API for EmailService service.
// All implementations must embed UnimplementedEmailServiceServer
// for forward compatibility
type EmailServiceServer interface {
	EmailService(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedEmailServiceServer()
}

// UnimplementedEmailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmailServiceServer struct {
}

func (UnimplementedEmailServiceServer) EmailService(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmailService not implemented")
}
func (UnimplementedEmailServiceServer) mustEmbedUnimplementedEmailServiceServer() {}

// UnsafeEmailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailServiceServer will
// result in compilation errors.
type UnsafeEmailServiceServer interface {
	mustEmbedUnimplementedEmailServiceServer()
}

func RegisterEmailServiceServer(s grpc.ServiceRegistrar, srv EmailServiceServer) {
	s.RegisterService(&EmailService_ServiceDesc, srv)
}

func _EmailService_EmailService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).EmailService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/src.EmailService/EmailService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).EmailService(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailService_ServiceDesc is the grpc.ServiceDesc for EmailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "src.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmailService",
			Handler:    _EmailService_EmailService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emailService/proto/email.proto",
}

// SendGridServiceClient is the client API for SendGridService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendGridServiceClient interface {
	SendGridService(ctx context.Context, in *SendgridRequest, opts ...grpc.CallOption) (*SendGridResponse, error)
}

type sendGridServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSendGridServiceClient(cc grpc.ClientConnInterface) SendGridServiceClient {
	return &sendGridServiceClient{cc}
}

func (c *sendGridServiceClient) SendGridService(ctx context.Context, in *SendgridRequest, opts ...grpc.CallOption) (*SendGridResponse, error) {
	out := new(SendGridResponse)
	err := c.cc.Invoke(ctx, "/src.SendGridService/SendGridService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendGridServiceServer is the server API for SendGridService service.
// All implementations must embed UnimplementedSendGridServiceServer
// for forward compatibility
type SendGridServiceServer interface {
	SendGridService(context.Context, *SendgridRequest) (*SendGridResponse, error)
	mustEmbedUnimplementedSendGridServiceServer()
}

// UnimplementedSendGridServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSendGridServiceServer struct {
}

func (UnimplementedSendGridServiceServer) SendGridService(context.Context, *SendgridRequest) (*SendGridResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGridService not implemented")
}
func (UnimplementedSendGridServiceServer) mustEmbedUnimplementedSendGridServiceServer() {}

// UnsafeSendGridServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendGridServiceServer will
// result in compilation errors.
type UnsafeSendGridServiceServer interface {
	mustEmbedUnimplementedSendGridServiceServer()
}

func RegisterSendGridServiceServer(s grpc.ServiceRegistrar, srv SendGridServiceServer) {
	s.RegisterService(&SendGridService_ServiceDesc, srv)
}

func _SendGridService_SendGridService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendgridRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendGridServiceServer).SendGridService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/src.SendGridService/SendGridService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendGridServiceServer).SendGridService(ctx, req.(*SendgridRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SendGridService_ServiceDesc is the grpc.ServiceDesc for SendGridService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendGridService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "src.SendGridService",
	HandlerType: (*SendGridServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendGridService",
			Handler:    _SendGridService_SendGridService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emailService/proto/email.proto",
}
